### ISSUE TITLE
The report should indicate age of most recent update

### ISSUE THREAD

**Issue by fginther** [fginther/review-gator#6]
The report show the age of PRs and the age of the review request. This is a bit meaningless once the PR has been updated. I think the age should reflect the most recent update (or include both).

The review age should show when the reviewer last commented. What it's showing now is meaningless.

This is impacting LP bzr and git repos. Don't know if github works differently.

**Comment by philroche** [comment]
This has been addressed in https://github.com/fginther/review-gator/pull/7
